compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -33,7 +33,7 @@ mkdir -p $CACHE_DIR
 
 # create default system.properties
 if [ ! -f ${BUILD_DIR}/system.properties ]; then
-  echo "java.runtime.version=1.6" > ${BUILD_DIR}/system.properties
+  echo "java.runtime.version=1.7" > ${BUILD_DIR}/system.properties
 fi
 
 # install JDK
@@ -62,17 +62,17 @@ for DIR in $CACHED_DIRS; do
 done
 
 # these are preliminary checks. actual version check happens below when attempting to download sbt boot.properties
-if ! test -e project/build.properties; then
-	echo " !      Error, your scala project must include project/build.properties and define sbt.version"
-	echo " !      You must use a release version of sbt, sbt.version=0.11.0 or greater"
-        exit 1
-fi
+#if ! test -e project/build.properties; then
+#	echo " !      Error, your scala project must include project/build.properties and define sbt.version"
+#	echo " !      You must use a release version of sbt, sbt.version=0.11.0 or greater"
+#        exit 1
+#fi
 
-if ! has_supported_sbt_version ${BUILD_DIR}; then
-	echo " !      Error, you have defined an unsupported sbt.version in project/build.properties"
-	echo " !      You must use a release version of sbt, sbt.version=0.11.0 or greater"
-	exit 1
-fi
+#if ! has_supported_sbt_version ${BUILD_DIR}; then
+#	echo " !      Error, you have defined an unsupported sbt.version in project/build.properties"
+#	echo " !      You must use a release version of sbt, sbt.version=0.11.0 or greater"
+#	exit 1
+#fi
 
 SBT_VERSION="$(get_supported_sbt_version ${BUILD_DIR})"
 SBT_JAR="sbt-launch.jar"
